version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 443:443
    volumes:
      - /ssl:/ssl
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/baimin/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dice-game
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
